# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='', upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='like_users',
            field=models.ManyToManyField(related_name='user_set_like_photos', through='photo.PhotoLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photocomment',
            name='photo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
            preserve_default=False,
        ),
    ]
