# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161111_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototag',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
