# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_phototag_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='like_users',
            field=models.ManyToManyField(related_name='user_set_like_users', through='photo.PhotoLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photo.PhotoTag'),
        ),
    ]
