# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:16
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20161111_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='upload'),
        ),
    ]
