# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20161111_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
